language: c
sudo: required
os:
- linux
compiler:
- gcc
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y -qq coreutils make autoconf automake gcc build-essential libelf-dev
script:
- make DEFCONFIG=y
